<?php

namespace Database\Seeders;

use App\Models\Order;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //name surname phone email address notes paid total
        $orders = [
            [
                'name' => 'Mario',
                'surname' => 'Rossi',
                'phone' => '1234567890',
                'email' => 'mario@example.com',
                'address' => 'Via Roma 1',
                'notes' => 'Consegna urgente',
                'paid' => true,
                'total' => 35.99,
            ],
            [
                'name' => 'Anna',
                'surname' => 'Bianchi',
                'phone' => '0987654321',
                'email' => 'anna@example.com',
                'address' => 'Corso Italia 10',
                'notes' => 'Pagamento con carta di credito',
                'paid' => false,
                'total' => 42.75,
            ],
            [
                'name' => 'Luca',
                'surname' => 'Verdi',
                'phone' => '2345678901',
                'email' => 'luca@example.com',
                'address' => 'Via Napoli 5',
                'notes' => 'Consegna in serata',
                'paid' => true,
                'total' => 28.50,
            ],
            [
                'name' => 'Sara',
                'surname' => 'Ferrari',
                'phone' => '3456789012',
                'email' => 'sara@example.com',
                'address' => 'Via Venezia 8',
                'notes' => 'Ritiro in loco',
                'paid' => false,
                'total' => 19.99,
            ],
            [
                'name' => 'Giorgio',
                'surname' => 'Russo',
                'phone' => '4567890123',
                'email' => 'giorgio@example.com',
                'address' => 'Piazza Garibaldi 12',
                'notes' => 'Consegna al piano',
                'paid' => true,
                'total' => 55.25,
            ],
            [
                'name' => 'Martina',
                'surname' => 'Gallo',
                'phone' => '5678901234',
                'email' => 'martina@example.com',
                'address' => 'Via Firenze 3',
                'notes' => 'Pagamento in contanti',
                'paid' => false,
                'total' => 38.75,
            ],
            [
                'name' => 'Giovanni',
                'surname' => 'Romano',
                'phone' => '6789012345',
                'email' => 'giovanni@example.com',
                'address' => 'Corso Vittorio Emanuele 7',
                'notes' => 'Consegna al portone',
                'paid' => true,
                'total' => 47.90,
            ],
            [
                'name' => 'Laura',
                'surname' => 'Marini',
                'phone' => '7890123456',
                'email' => 'laura@example.com',
                'address' => 'Via Carducci 15',
                'notes' => 'Ritiro entro le ore 20',
                'paid' => false,
                'total' => 63.20,
            ],
            [
                'name' => 'Simone',
                'surname' => 'Moretti',
                'phone' => '8901234567',
                'email' => 'simone@example.com',
                'address' => 'Via Garibaldi 20',
                'notes' => 'Consegna da concordare',
                'paid' => true,
                'total' => 29.99,
            ],
            [
                'name' => 'Francesca',
                'surname' => 'Conti',
                'phone' => '9012345678',
                'email' => 'francesca@example.com',
                'address' => 'Piazza Duomo 2',
                'notes' => 'Ritiro dopo le 18',
                'paid' => false,
                'total' => 45.50,
            ],
            [
                'name' => 'Giovanni',
                'surname' => 'Russo',
                'phone' => '4567890123',
                'email' => 'giovanni@example.com',
                'address' => 'Via Firenze 15',
                'notes' => 'Senza glutine',
                'paid' => true,
                'total' => 39.99,
            ],
            [
                'name' => 'Laura',
                'surname' => 'Gallo',
                'phone' => '5678901234',
                'email' => 'laura@example.com',
                'address' => 'Corso Milano 20',
                'notes' => 'Orario di consegna preferito: dopo le 18:00',
                'paid' => false,
                'total' => 55.25,
            ],
            [
                'name' => 'Marco',
                'surname' => 'Costa',
                'phone' => '6789012345',
                'email' => 'marco@example.com',
                'address' => 'Via Torino 12',
                'notes' => 'Da preparare senza lattosio',
                'paid' => true,
                'total' => 32.75,
            ],
            [
                'name' => 'Giulia',
                'surname' => 'Martini',
                'phone' => '7890123456',
                'email' => 'giulia@example.com',
                'address' => 'Piazza Garibaldi 3',
                'notes' => 'Consegna al piano',
                'paid' => false,
                'total' => 47.80,
            ],
            [
                'name' => 'Paolo',
                'surname' => 'Conti',
                'phone' => '8901234567',
                'email' => 'paolo@example.com',
                'address' => 'Via Roma 30',
                'notes' => 'Da imballare con cura',
                'paid' => true,
                'total' => 25.50,
            ],
            [
                'name' => 'Carlo',
                'surname' => 'Ferrari',
                'phone' => '3456789012',
                'email' => 'carlo@example.com',
                'address' => 'Via Verdi 18',
                'notes' => 'Consegna urgente',
                'paid' => false,
                'total' => 42.99,
            ],
            [
                'name' => 'Francesca',
                'surname' => 'Bianchi',
                'phone' => '4567890123',
                'email' => 'francesca@example.com',
                'address' => 'Corso Italia 25',
                'notes' => 'Orario di consegna preferito: prima delle 12:00',
                'paid' => true,
                'total' => 29.75,
            ],
            [
                'name' => 'Alessandro',
                'surname' => 'Ricci',
                'phone' => '5678901234',
                'email' => 'alessandro@example.com',
                'address' => 'Piazza Duomo 10',
                'notes' => 'Pagamento in contanti alla consegna',
                'paid' => false,
                'total' => 35.20,
            ],
            [
                'name' => 'Elisa',
                'surname' => 'Moretti',
                'phone' => '6789012345',
                'email' => 'elisa@example.com',
                'address' => 'Via Garibaldi 5',
                'notes' => 'Richiesta aggiunta di formaggio extra',
                'paid' => true,
                'total' => 38.50,
            ],
            [
                'name' => 'Simone',
                'surname' => 'Galli',
                'phone' => '7890123456',
                'email' => 'simone@example.com',
                'address' => 'Via Napoli 22',
                'notes' => 'Consegna al portone',
                'paid' => false,
                'total' => 50.00,
            ],
            [
                'name' => 'Chiara',
                'surname' => 'Rossi',
                'phone' => '8901234567',
                'email' => 'chiara@example.com',
                'address' => 'Via Roma 15',
                'notes' => 'Consegna dopo le 18:00',
                'paid' => true,
                'total' => 27.80,
            ],
            [
                'name' => 'Giacomo',
                'surname' => 'Conte',
                'phone' => '9012345678',
                'email' => 'giacomo@example.com',
                'address' => 'Via Venezia 8',
                'notes' => 'Nessuna nota aggiuntiva',
                'paid' => false,
                'total' => 21.30,
            ],
            [
                'name' => 'Martina',
                'surname' => 'Marini',
                'phone' => '0123456789',
                'email' => 'martina@example.com',
                'address' => 'Via Firenze 12',
                'notes' => 'Consegna al terzo piano',
                'paid' => true,
                'total' => 45.60,
            ],
            [
                'name' => 'Paolo',
                'surname' => 'Rizzo',
                'phone' => '1234567890',
                'email' => 'paolo@example.com',
                'address' => 'Via Milano 30',
                'notes' => 'Ritiro in negozio',
                'paid' => false,
                'total' => 33.75,
            ],
            [
                'name' => 'Elena',
                'surname' => 'Costa',
                'phone' => '2345678901',
                'email' => 'elena@example.com',
                'address' => 'Via Torino 7',
                'notes' => 'Pagamento online con carta di credito',
                'paid' => true,
                'total' => 28.90,
            ],
            [
                'name' => 'Luigi',
                'surname' => 'Verdi',
                'phone' => '3456789012',
                'email' => 'luigi@example.com',
                'address' => 'Via Napoli 20',
                'notes' => 'Consegna urgente entro le 18:00',
                'paid' => true,
                'total' => 39.50,
            ],
            [
                'name' => 'Maria',
                'surname' => 'Ferrari',
                'phone' => '4567890123',
                'email' => 'maria@example.com',
                'address' => 'Via Palermo 5',
                'notes' => 'Ritiro presso ufficio postale',
                'paid' => false,
                'total' => 17.90,
            ],
            [
                'name' => 'Alessio',
                'surname' => 'Russo',
                'phone' => '5678901234',
                'email' => 'alessio@example.com',
                'address' => 'Via Genova 3',
                'notes' => 'Consegna al portone',
                'paid' => true,
                'total' => 23.75,
            ],
            [
                'name' => 'Giulia',
                'surname' => 'Bianchi',
                'phone' => '6789012345',
                'email' => 'giulia@example.com',
                'address' => 'Via Roma 18',
                'notes' => 'Pagamento in contanti al corriere',
                'paid' => false,
                'total' => 31.20,
            ],
            [
                'name' => 'Marco',
                'surname' => 'Gallo',
                'phone' => '7890123456',
                'email' => 'marco@example.com',
                'address' => 'Via Firenze 24',
                'notes' => 'Consegna in orario lavorativo',
                'paid' => true,
                'total' => 42.80,
            ],
            [
                'name' => 'Chiara',
                'surname' => 'Rossi',
                'phone' => '8901234567',
                'email' => 'chiara@example.com',
                'address' => 'Via Venezia 12',
                'notes' => 'Consegna entro venerdì',
                'paid' => true,
                'total' => 55.00,
            ],
            [
                'name' => 'Fabio',
                'surname' => 'Conti',
                'phone' => '9012345678',
                'email' => 'fabio@example.com',
                'address' => 'Corso Milano 7',
                'notes' => 'Ritiro presso portineria',
                'paid' => false,
                'total' => 20.50,
            ],
            [
                'name' => 'Elena',
                'surname' => 'Martini',
                'phone' => '0123456789',
                'email' => 'elena@example.com',
                'address' => 'Via Torino 15',
                'notes' => 'Pagamento con carta di credito',
                'paid' => true,
                'total' => 37.80,
            ],
            [
                'name' => 'Luca',
                'surname' => 'Santini',
                'phone' => '1234567890',
                'email' => 'luca@example.com',
                'address' => 'Via Parma 9',
                'notes' => 'Consegna al cancello',
                'paid' => false,
                'total' => 28.75,
            ],
            [
                'name' => 'Sara',
                'surname' => 'Moretti',
                'phone' => '2345678901',
                'email' => 'sara@example.com',
                'address' => 'Via Catania 21',
                'notes' => 'Consegna urgente',
                'paid' => true,
                'total' => 48.90,
            ],
            [
                'name' => 'Marco',
                'surname' => 'Bianchi',
                'phone' => '3456789012',
                'email' => 'marco@example.com',
                'address' => 'Via Roma 3',
                'notes' => 'Consegna al portone',
                'paid' => true,
                'total' => 65.00,
            ],
            [
                'name' => 'Anna',
                'surname' => 'Verdi',
                'phone' => '4567890123',
                'email' => 'anna@example.com',
                'address' => 'Via Firenze 8',
                'notes' => 'Pagamento in contanti',
                'paid' => false,
                'total' => 30.25,
            ],
            [
                'name' => 'Francesco',
                'surname' => 'Ricci',
                'phone' => '5678901234',
                'email' => 'francesco@example.com',
                'address' => 'Via Napoli 14',
                'notes' => 'Orario preferito dopo le 18:00',
                'paid' => true,
                'total' => 42.75,
            ],
            [
                'name' => 'Elisa',
                'surname' => 'Gallo',
                'phone' => '6789012345',
                'email' => 'elisa@example.com',
                'address' => 'Via Palermo 23',
                'notes' => 'Ritiro al punto di ritiro stabilito',
                'paid' => false,
                'total' => 22.90,
            ],
            [
                'name' => 'Davide',
                'surname' => 'Costa',
                'phone' => '7890123456',
                'email' => 'davide@example.com',
                'address' => 'Via Genova 17',
                'notes' => 'Consegna urgente entro domani',
                'paid' => true,
                'total' => 53.50,
            ],
            [
                'name' => 'Giulia',
                'surname' => 'Rossi',
                'phone' => '8901234567',
                'email' => 'giulia@example.com',
                'address' => 'Via Milano 5',
                'notes' => 'Consegna al cancello principale',
                'paid' => true,
                'total' => 47.80,
            ],
            [
                'name' => 'Fabio',
                'surname' => 'Martini',
                'phone' => '9012345678',
                'email' => 'fabio@example.com',
                'address' => 'Via Torino 12',
                'notes' => 'Richiesta di consegna rapida',
                'paid' => false,
                'total' => 38.20,
            ],
            [
                'name' => 'Chiara',
                'surname' => 'Ferrari',
                'phone' => '0123456789',
                'email' => 'chiara@example.com',
                'address' => 'Via Bologna 20',
                'notes' => 'Pagamento tramite carta di credito',
                'paid' => true,
                'total' => 56.70,
            ],
            [
                'name' => 'Luigi',
                'surname' => 'Bianco',
                'phone' => '1234567890',
                'email' => 'luigi@example.com',
                'address' => 'Via Venezia 8',
                'notes' => 'Ritiro presso il negozio',
                'paid' => false,
                'total' => 25.40,
            ],
            [
                'name' => 'Sara',
                'surname' => 'Neri',
                'phone' => '2345678901',
                'email' => 'sara@example.com',
                'address' => 'Via Roma 33',
                'notes' => 'Consegna in orario serale',
                'paid' => true,
                'total' => 62.90,
            ],
            [
                'name' => 'Alessandro',
                'surname' => 'Verdi',
                'phone' => '3456789012',
                'email' => 'alessandro@example.com',
                'address' => 'Via Firenze 15',
                'notes' => 'Consegna al portone principale',
                'paid' => true,
                'total' => 53.50,
            ],
            [
                'name' => 'Elena',
                'surname' => 'Bianchi',
                'phone' => '4567890123',
                'email' => 'elena@example.com',
                'address' => 'Corso Vittorio Emanuele 28',
                'notes' => 'Pagamento in contanti alla consegna',
                'paid' => false,
                'total' => 42.80,
            ],
            [
                'name' => 'Marco',
                'surname' => 'Russo',
                'phone' => '5678901234',
                'email' => 'marco@example.com',
                'address' => 'Via Padova 9',
                'notes' => 'Consegna con imballo regalo',
                'paid' => true,
                'total' => 37.90,
            ],
            [
                'name' => 'Giorgia',
                'surname' => 'Gallo',
                'phone' => '6789012345',
                'email' => 'giorgia@example.com',
                'address' => 'Via Garibaldi 36',
                'notes' => 'Richiesta di contorno extra',
                'paid' => false,
                'total' => 28.60,
            ],
            [
                'name' => 'Simone',
                'surname' => 'Costa',
                'phone' => '7890123456',
                'email' => 'simone@example.com',
                'address' => 'Via Genova 22',
                'notes' => 'Consegna in ufficio',
                'paid' => true,
                'total' => 45.70,
            ],
        ];
        foreach ($orders as $order) {
            $newOrder = new Order();
            $newOrder->fill($order);
            $newOrder->save();
        }
    }
}
